version: '3.9'
services:
  staff-fm-db:
    image: mongo
    container_name: staff-fm-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/mongodb
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${DB_ROOT_NAME}
      MONGO_USERNAME: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASS}
      MONGO_DATABASE: ${DB_NAME}
    networks:
      staff-fm-network:

  staff-fm-cache:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      staff-fm-network:

  staff-fm-bot:
    container_name: staff-fm-bot
    build: .
    env_file:
      - .env
    restart: on-failure:8
    networks:
      staff-fm-network:

networks:
  staff-fm-network:
    driver: bridge

volumes:
  mongodb: